-- phpMyAdmin SQL Dump
-- version 5.2.2
-- https://www.phpmyadmin.net/
--
-- Servidor: localhost:3306
-- Tiempo de generación: 22-02-2026 a las 21:16:40
-- Versión del servidor: 11.4.9-MariaDB-cll-lve-log
-- Versión de PHP: 8.3.29

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Base de datos: `codehwsn_mallorquin_market`
--

-- --------------------------------------------------------

--
-- Estructura de tabla para la tabla `producto`
--

CREATE TABLE `producto` (
  `id_producto` int(10) NOT NULL,
  `codigo_barras_producto` bigint(13) DEFAULT NULL,
  `marca_producto` enum('--','Advil','Anyeluz','Bayer','Carefree','Dolex','Ego','Essence','Eterna','Genérico','Gillette','Haleon','Huggies','Johnson''s','Kadio','Kotex','Listerine','Lubriderm','Marfil','Masglo','Medicasp','Mexsana','Milagros','Mon Ami','Nivea','Nosotras','Nude','Nutribela','Pequeñín','Rexona','Ruby Rose','Rumatex','Scribe','Sedal','Speed Stick','Sundown','Tío Nacho','Trendy Boom','VapoRup','Vogue') CHARACTER SET utf8mb3 COLLATE utf8mb3_spanish_ci NOT NULL,
  `nombre_producto` text CHARACTER SET utf8mb3 COLLATE utf8mb3_spanish_ci NOT NULL,
  `descripcion_producto` text CHARACTER SET utf8mb3 COLLATE utf8mb3_spanish_ci NOT NULL,
  `precio_producto` int(10) NOT NULL,
  `imagen_producto` varchar(10) CHARACTER SET utf8mb3 COLLATE utf8mb3_spanish_ci NOT NULL,
  `categoria_producto` enum('celebraciones','cosmeticos','cuidado-personal','farmacia','mascotas','miscelaneos','papelería') NOT NULL,
  `disponibilidad_producto` tinyint(1) NOT NULL,
  `destacado_producto` tinyint(1) NOT NULL,
  `nuevo_producto` tinyint(1) NOT NULL,
  `proveedor_producto` varchar(50) CHARACTER SET utf8mb3 COLLATE utf8mb3_spanish_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

--
-- Volcado de datos para la tabla `producto`
--

INSERT INTO `producto` (`id_producto`, `codigo_barras_producto`, `marca_producto`, `nombre_producto`, `descripcion_producto`, `precio_producto`, `imagen_producto`, `categoria_producto`, `disponibilidad_producto`, `destacado_producto`, `nuevo_producto`, `proveedor_producto`) VALUES
(1, 7509552840261, 'Vogue', 'Pestañina Vogue a Prueba De Agua Amor a Primera Vista x 9g', 'Volumen impactante a prueba de agua. \nEnamórate de tus pestañas con la Máscara Amor a Primera Vista, Disfruta de un 91% de volumen impactante, 93% pestañas más largas y curvas, durante todo el día.', 25000, '1.webp', 'cosmeticos', 1, 1, 1, 'Novaventa'),
(2, 7702026313814, 'Pequeñín', 'Toallitas Húmedas Pequeñín Aloe x 100 unds', 'Humectan la piel y ofrecen un cuidado refrescante gracias a su fórmula con aloe que además les dará un toque de frescura que a ellos les encantará. - Súper acolchadas: su tela super acolchada ofrece una limpieza avanzada Contiene: 100 unidades de toallitas húmedas', 12000, '2.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(3, 650240073526, 'Tío Nacho', 'Shampoo Tío Nacho Anti-caída Reparación Profunda Keratina Vegetal x 415ml', 'Con el poder de la naturaleza, nutre, fortalece y reduce puntas abiertas. Reparación profunda con jalea real + Keratina Vegetal. 0% parabenos y siliconas.', 30000, '3.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(4, 7707977663315, 'Anyeluz', 'Fijador De Cejas Anyeluz Tono Castaño Claro x 5.3ml', 'Define tu mirada con precisión. El fijador Anyeluz Castaño Claro peina, fija y rellena espacios con un acabado sutil y natural. Fórmula de larga duración, sin sensación pegajosa, para cejas impecables todo el día.', 12000, '4.webp', 'cosmeticos', 1, 1, 1, 'Novaventa'),
(5, 7891010250713, 'Sundown', 'Protector Solar Sundown Playa y Piscina FPS70 x 120ml', 'Protección extrema para tus días de sol. Sundown Playa y Piscina FPS70 ofrece alta resistencia al agua y al sudor. Hidrata y previene el envejecimiento prematuro, ideal para toda la familia. ¡Protección segura por más tiempo!', 58000, '5.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(6, 7702031291565, 'Johnson\'s', 'Shampoo Johnson\'s Original  con glicerina y vitamina B5 x200ml', 'Limpieza suave con fórmula No Más Lágrimas, ideal para los ojos del bebé. pH equilibrado, sin jabón ni alcohol. Hipoalergénico y dermatológicamente probado. Cabello limpio, suave y con el aroma clásico que amas.', 20000, '6.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(7, 7702031244608, 'Johnson\'s', 'Polvo Johnson\'s Baby Original x 400g', 'El cuidado más puro para tu bebé. Absorbe el exceso de humedad, manteniendo la piel seca, fresca y protegida contra irritaciones. Fórmula clásica clínicamente probada y aroma inconfundible. Ideal para cada cambio de pañal.', 55000, '7.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(8, 7506306214989, 'Rexona', 'Desodorante Rexona Clinical Classic 3X Aerosol Mujer x 150ml', 'Máxima protección con tecnología que forma un escudo contra el sudor y mal olor. Nivel Clinical Classic en aerosol: 3 veces más potente que un antitranspirante común. Frescura intensa y cuidado para tu piel todo el día.', 26000, '8.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(9, 7506306214972, 'Rexona', 'Desodorante Rexona Clinical Clean 3X Aerosol Hombre x 150ml', 'Máxima eficacia contra el sudor excesivo. Su tecnología Clinical 3X ofrece protección superior en aerosol, combatiendo el mal olor bajo condiciones extremas. Secado rápido y fragancia masculina para una seguridad imparable.', 26000, '9.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(10, 7702123011545, 'Mexsana', 'Desodorante para pies Mexsana  Clásico Aerosol x 260ml', 'El aliado experto contra el sudor y mal olor. Mexsana Clásico ofrece alta protección, manteniendo tus pies secos y frescos por más tiempo. Su formato aerosol de 260ml garantiza mayor duración y una aplicación rápida.', 21000, '10.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(11, 7702123011521, 'Mexsana', 'Desodorante para pies Mexsana Lady Aerosol x 260ml', 'Protección delicada y aroma femenino para tus pies. Mexsana Lady combate el sudor y mal olor sin dejar huella. Su aplicación en spray es fácil, rápida y garantiza pies frescos y secos todo el día. ¡Cuidado ideal para tu piel!', 21000, '11.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(12, 7702132009731, 'Advil', 'Advil Children Suspensión x 60ml', 'Alivio rápido y efectivo para tu pequeño. Advil Children brinda hasta 8 horas de alivio contra la fiebre y el dolor. Incluye jeringa dosificadora para una administración exacta y segura. ¡Ayúdalos a jugar y descansar tranquilos!', 25000, '12.webp', 'farmacia', 1, 1, 1, 'Novaventa'),
(13, 7707977663599, 'Anyeluz', 'Fijador De Cejas Anyeluz Tono Castaño Oscuro x 5.3ml', 'Logra cejas de impacto con definición y profundidad. Anyeluz Castaño Oscuro fija, peina y rellena sutilmente para un aspecto poblado y uniforme. Fórmula de secado rápido, sin residuos blancos ni sensación pesada.', 12000, '13.webp', 'cosmeticos', 1, 1, 1, 'Novaventa'),
(14, 7702354952341, 'Nutribela', 'Tratamiento Capilar Nutribela con Células Madre x 300ml', 'Revitaliza tu cabello desde la raíz. Nutribela Células Madre ofrece nutrición profunda y control caída. Su fórmula innovadora restaura el brillo y la vitalidad, dejando el pelo hidratado y fuerte.', 19000, '14.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(15, 7702425406971, 'Kotex', 'Protectores Diarios Kotex Largos x 120 unds', 'Protección extendida y frescura diaria en un diseño largo, delgado y discreto. Fabricados con materiales suaves que cuidan tu zona íntima brindando máxima comodidad. Ideal para sentirte segura y limpia todo el día.', 22000, '15.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(16, 7900083011593, 'Ruby Rose', 'Rubor En Barra Ruby Rose Tono Frosted Rose x 6.57g', '¡Dale a tus mejillas un toque de frescura al instante! El rubor en barra de Ruby Rose en el tono Frosted Rose ofrece una textura cremosa que se desliza suavemente sobre la piel, brindando un acabado natural y radiante. Su formato en barra es perfecto para llevar en el bolso y retocar tu maquillaje en cualquier momento. Es fácil de difuminar, de larga duración y se adapta perfectamente a diferentes tonos de piel, dejando un aspecto saludable y juvenilDale color y frescura a tu rostro con el Rubor en Barra Ruby Rose. Su tono Frosted Rose ofrece un acabado natural y radiante. Formato práctico de 6.57g, fácil de difuminar y llevar a todas partes. ¡Resalta tu belleza!', 27000, '16.webp', 'cosmeticos', 1, 1, 1, 'Novaventa'),
(17, 7702031244523, 'Lubriderm', 'Crema Corporal Lubriderm Humectación Diaria x 946ml', 'Mantiene la humectación en piel normal y seca. Clínicamente comprobada para humectar hasta por 48 horas. Repara y refresca la piel dejándola visiblemente saludable en menos de 1 día. Úsala en cuerpo y cara.', 55000, '17.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(18, 18, 'Milagros', 'Acondicionador Milagros Arroz y Linaza x 450ml', '¡El secreto natural para un cabello invencible! El Acondicionador Milagros combina las bondades del Arroz y la Linaza para ofrecer una hidratación profunda y restaurar la elasticidad de la fibra capilar. Su fórmula única ayuda a sellar la cutícula, controlar el frizz y aportar un brillo extraordinario sin dejar el cabello pesado. Es ideal para todo tipo de melenas, especialmente aquellas que buscan suavidad extrema y un desenredo fácil después del lavado.', 35000, '18.webp', 'cuidado-personal', 0, 0, 0, 'Novaventa'),
(19, 7501001109660, 'Gillette', 'Maquina de afeitar Gillette Prestobarba3 Mujer x 4 unds', 'Esta máquina de afeitar desechable para mujer, deja tu piel tan suave como una seda. Tiene un cabezal móvil de 3 hojas montadas sobre resortes independientes, banda lubricante y mango de agarre suave. Ideal para ajustarse a los contornos de tu cuerpo para lograr una afeitada suave y al ras en pocas pasadasDepilación suave y al ras con 3 hojas alineadas. La Prestobarba3 para mujer tiene banda lubricante con aceites botánicos para evitar irritación. Cabezal móvil que se adapta a tus curvas. ¡Pack de 4 para mayor ahorro!', 25000, '19.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(20, 7702354958114, 'Nutribela', 'Shampoo Nutribela Biokeratina x400ml', 'Limpieza profunda y restauración avanzada. Nutribela Biokeratina nutre y fortalece el cabello dañado, devolviendo el brillo y la suavidad natural. Formato de 400ml ideal para el cuidado diario. ¡Cabello fuerte y manejable!', 22000, '20.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(21, 7509552956924, 'Vogue', 'Esmalte Para Uñas Vogue Secado Rápido Tono Ena-morada x 12ml', 'Logra uñas impecables en minutos. El Esmalte Vogue Secado Rápido ofrece color intenso y brillo duradero en el tono Ena-morada. Su pincel plano facilita la aplicación uniforme. ¡Secado instantáneo para un acabado profesional!', 8500, '21.webp', 'cosmeticos', 1, 1, 1, 'Novaventa'),
(22, 7702354956288, 'Nutribela', 'Acondicionador Prohialurónico Nutribela x 370ml', 'Nutribela Prohialurónico Fuerza y Crecimiento desenreda suavemente mientras rellena la fibra capilar, dejando un brillo intenso y suavidad extrema. Formato de 370ml para uso diario.', 22000, '22.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(23, 650240029158, 'Medicasp', 'Shampoo Medicasp 2% x 100ml', 'Solución efectiva contra la caspa y el hongo que la produce. Medicasp alivia la picazón y el ardor desde el primer uso. Su fórmula con Ketoconazol 2% restaura la salud del cuero cabelludo. ¡Eficacia clínica en 100ml!', 30000, '23.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(24, 7702425837706, 'Kotex', 'Toallas higiénicas Kotex Ultraprotect  x 24 unds', 'Máxima seguridad y discreción en tus días. Las Kotex Ultraprotect ofrecen absorción rápida y ajuste perfecto al cuerpo para evitar filtraciones. Su cubierta suave cuida tu piel. ¡Paquete ahorro de 24 unidades!', 12000, '24.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(25, 7709094542184, 'Trendy Boom', 'Pestañina Lavable Trendy Boom x 15ml', '¡Explosión de volumen y longitud! La pestañina Trendy Boom tiene un cepillo de silicona que separa cada pestaña sin dejar grumos. Fórmula lavable de fácil retiro, ideal para el uso diario sin maltratar tus pestañas.', 15000, '25.webp', 'cosmeticos', 1, 1, 1, 'Novaventa'),
(26, 7891010031046, 'Johnson\'s', 'Aceite Johnson\'s Baby Original x 100ml', 'Suavidad pura para la piel de tu bebé. El Aceite Johnson\'s Baby Original retiene hasta 10 veces más hidratación, dejando la piel protegida y libre de impurezas. Fórmula hipoalergénica y suave, ideal para masajes diarios.', 16500, '26.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(27, 7707773834704, 'Masglo', 'Base Para uñas Masglo Ajo Y Limón x 13.5ml', 'Fortalece tus uñas de forma natural. La Base Masglo Ajo y Limón ayuda a endurecer las uñas débiles y quebradizas, previniendo que se partan. Fórmula enriquecida para un crecimiento sano y una manicura duradera.', 10600, '27.webp', 'cosmeticos', 1, 1, 1, 'Novaventa'),
(28, 7500435107013, 'VapoRup', 'Vick VapoRub x 50g', 'El aliado clásico de la familia para las noches de descanso. Vick VapoRub es un ungüento que combina el poder del mentol, eucalipto y alcanfor para aliviar rápidamente la congestión nasal, la tos y los dolores musculares causados por el resfriado. Al aplicarlo sobre el pecho, cuello y espalda, sus vapores medicinales actúan profundamente para ayudarte a respirar mejor y recuperar el bienestar. Su formato de 50g es el tamaño perfecto para tener siempre a mano en el hogar.', 21500, '28.webp', 'farmacia', 1, 1, 1, 'Novaventa'),
(29, 7509552956948, 'Vogue', 'Esmalte Para Uñas Vogue Secado Rápido Tono Amo-rosa x 12ml', 'Logra uñas impecables en minutos. El Esmalte Vogue Secado Rápido ofrece color intenso y brillo duradero en el tono Amo-rosa. Su pincel plano facilita la aplicación uniforme. ¡Secado instantáneo para un acabado profesional!', 8500, '29.webp', 'cosmeticos', 1, 1, 1, 'Novaventa'),
(30, 7702006298940, 'Ego', 'Gel Pote Ego Attraction x 110ml', 'Máxima fijación con fragancia masculina irresistible. El Gel Ego Attraction mantiene tu peinado firme durante todo el día sin dejar residuos blancos ni sensación pegajosa. Ideal para un look definido y duradero.', 4200, '30.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(31, 4059729382412, 'Essence', 'Tinta Para Labios Y Mejillas Essence Tono 01 x 4.9ml', '¡A prueba de besos! Tinta 2 en 1 para labios y mejillas de larga duración. Fórmula ligera, no pegajosa y modulable para un acabado natural. Con aplicador biselado para retoques rápidos. ¡Color intenso que no se corre!', 21000, '31.webp', 'cosmeticos', 1, 1, 1, 'Novaventa'),
(32, 7269321103842, 'Ruby Rose', 'Lip Oil Para Labios Ruby Rose Tono Sandia x 5.5ml', 'Hidratación profunda con un toque de color y aroma a sandía. El Lip Oil Ruby Rose deja tus labios suaves, brillantes y sin sensación pegajosa. Su aplicador XL facilita una cobertura total en segundos. ¡Brillo natural!', 20000, '32.webp', 'cosmeticos', 1, 1, 1, 'Novaventa'),
(33, 7708075180704, 'Milagros', 'Shampoo Milagros Herbal x 450ml', 'Limpieza profunda con extractos herbales que fortalecen la fibra capilar. El Shampoo Milagros Herbal controla la grasa y estimula el crecimiento, dejando el cabello suelto y brillante. ¡Fórmula natural para un pelo sano!', 36000, '33.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(34, 7702354956219, 'Nutribela', 'Shampoo Nutribela Reparación Intensiva x 400ml', '¡Reparación total para cabello dañado! El Shampoo Nutribela combina 10 ingredientes poderosos (Biotina, Queratina, Argán y más) para restaurar la vitalidad y suavidad. Nutrición profunda desde la raíz en 400ml.', 21000, '34.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(35, 4059729394583, 'Essence', 'Brillo Essence Juicy Bomb Shiny Tono 103 x 10ml', 'Añade un toque brillante y jugoso a tus labios con el brillo Juicy Bomb Shiny de Essence. - Brillo labial con acabado brillante - Tono: Tono 103 - Marca: Essence', 9200, '35.webp', 'cosmeticos', 1, 1, 1, 'Novaventa'),
(36, 7702132008444, 'Advil', 'Advil Ultra x 10 capsulas', 'Alivio ultra rápido contra dolores fuertes: cabeza, muscular, espalda y articular. Gracias a su tecnología de cápsula líquida, Advil Ultra actúa más rápido que las tabletas comunes. ¡Eficacia potente en minutos!', 25000, '36.webp', 'farmacia', 1, 1, 1, 'Novaventa'),
(37, 7702006206815, 'Rexona', 'Desodorante tubo Rexona Clinical Mujer x 30g', '3 veces más protección contra el sudor y el mal olor. Rexona Clinical ofrece una fórmula cremosa que cuida tu piel mientras te mantiene seca y fresca en situaciones de estrés. ¡Eficacia dermatológica en formato 30g!', 4500, '37.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(38, 7751493010818, 'Kotex', 'Toallas Higiénicas Kotex Nocturnas extra suaves  x 24 unds', 'Máxima protección y suavidad para noches tranquilas. Las Kotex Nocturnas Extra largas con alas para evitar filtraciones mientras duermes. Su cubierta tipo algodón cuida tu piel.', 19000, '38.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(39, 7702425805187, 'Huggies', 'Toallitas húmedas Huggies Limpieza diaria x 80 unds', 'Limpieza suave y efectiva para la piel de tu bebé. Las toallitas Huggies Limpieza Diaria contienen fibras naturales que arrastran la suciedad sin irritar. Fórmula sin alcohol ni parabenos. ¡Paquete ahorro de 80 unidades!', 7000, '39.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(40, 7791969850616, 'Nivea', 'Bálsamo para labios Nivea Original x 4.8g', 'Labios suaves y protegidos por 24 horas. El bálsamo Nivea Original Care con manteca de karité y aceites naturales previene la sequedad y fortalece la barrera de tus labios. Fórmula transparente y ligera de 4.8g.', 22000, '40.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(41, 4005808377534, 'Nivea', 'Bálsamo Para Labios Nivea Cereza x 4.8g', 'Labios suaves y protegidos por 24 horas. El bálsamo Nivea Cherry Shine con manteca de karité y aceites naturales enriquecidos con vitaminas previene la sequedad y fortalece la barrera de la piel de tus labios.', 22000, '41.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(42, 79400301161, 'Rexona', 'Desodorante Rexona Clinical Extra Dry crema mujer x 48g', 'Protección extrema contra el sudor excesivo. Rexona Clinical Extra Dry ofrece una fórmula en crema con tecnología avanzada que forma una barrera protectora sobre la piel. Eficacia clínica hasta por 96 horas.', 28000, '42.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(43, 79400052919, 'Rexona', 'Desodorante Rexona Clinical Clean crema Hombre x 48g', 'Protección extrema para el hombre activo. Rexona Clinical Clean ofrece 3 veces más protección contra el sudor y el mal olor que un antitranspirante común. Su fórmula en crema brinda una sensación de frescura intensa y duradera.', 28000, '43.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(44, 44, 'Milagros', 'Shampoo Milagros Arroz y Acido Hialurónico x 450ml', 'El Shampoo Milagros arroz y ácido hialurónico de 450ml es una verdadera fuente de hidratación, nutrición y reparación para cabellos maltratados. Libre de parabenos, siliconas y sal, este shampoo promueve el crecimiento capilar, disminuye la caída y brinda una intensa reparación. Su fórmula única con arroz y ácido hialurónico fortalece el cabello y le devuelve su vitalidad. Producto exclusivo Novaventa. - El resultado: Desenreda mientras nutre a profundidad el cabello, fortalece, recupera y revitaliza gracias a su potente formulación. - Iingredientes: Aminoácidos, aceite de semillas de lino, extracto de arroz y linaza. - Recomendado: Para todo tipo de cabello, sobre todo, los más maltratados.', 35000, '44.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(45, 45, 'Bayer', 'Aspirina 100 x 28 Tabletas', 'Su presentación de 28 tabletas está diseñada para cubrir un ciclo mensual de tratamiento preventivo, ayudando a mejorar la circulación y reducir riesgos bajo indicación médica. Un producto esencial en el botiquín de quienes priorizan su salud a largo plazo.', 20000, '45.webp', 'farmacia', 1, 1, 1, 'Novaventa'),
(46, 46, 'Dolex', 'Dolex Forte x 10 Tabletas', 'Cuando el dolor requiere una solución superior, Dolex Forte es tu mejor aliado. Gracias a su fórmula reforzada con cafeína, actúa como un potenciador que acelera y aumenta el efecto analgésico del acetaminofén. Ideal para combatir dolores de cabeza intensos, migrañas, dolor de muela y dolores musculares fuertes. Una presentación práctica de 10 tabletas para llevar siempre contigo y no dejar que nada te detenga.', 21000, '46.webp', 'farmacia', 1, 1, 1, 'Novaventa'),
(47, 47, 'Bayer', 'Aspirina Efervescente x 12 Tabletas', 'Aspirina Efervescente combina el poder analgésico del ácido acetilsalicílico con una rápida disolución que facilita la absorción en el organismo. Es la solución ideal para aliviar el dolor de cabeza, molestias musculares y síntomas del resfriado, brindando además una sensación de alivio estomacal gracias a su formato efervescente. Un clásico que no puede faltar en tu hogar para actuar rápido ante cualquier malestar.', 18000, '47.webp', 'farmacia', 1, 1, 1, 'Novaventa'),
(48, 48, 'Johnson\'s', 'Shampoo Johnson\'s Cabello Oscuro x 200ml', ' Con extracto natural de mora, que ayuda a proteger el pelo oscuro del bebé. Con más del 90% de ingredientes de origen natural. Limpia suave y efectivamente el cuero cabelludo y pelo del bebé. Tiene el pH fisiológico ideal para limpiar suavemente su cuero cabelludo. Es hipoalergénico y libre de colorantes, parabenos, sulfatos y ftalatos. Fórmula \"No más lágrimas\".', 20000, '48.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(49, 49, 'Nude', 'Protector Solar Nude para cara y cuerpo SPF60 x 90ml36', 'El Protector Solar Nude SPF 60 es un producto estratégico para Mallorquín Market, especialmente considerando el clima de Barranquilla y Ciudad Mallorquín. Al ser un producto de uso diario tanto para adultos como para niños, su descripción debe resaltar la protección total y la textura agradable.  Aquí tienes las opciones para tu catálogo:  Opción 1: Enfoque en Cuidado Familiar (Ideal para catálogo) Título: Protector Solar Nude Cara y Cuerpo SPF 60 x 90 ml  Descripción: > Brinda a tu piel la máxima defensa contra los rayos UVA y UVB. El protector solar Nude SPF 60 ofrece una fórmula de alta eficacia que previene el envejecimiento prematuro y las manchas causadas por el sol. Su textura ligera y de rápida absorción es ideal tanto para el rostro como para el cuerpo, sin dejar sensación grasosa ni rastro blanco. Es el aliado perfecto para la protección diaria de toda la familia, asegurando una piel hidratada y saludable bajo el sol.', 28000, '49.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(50, 50, 'Essence', 'Brillo Essence Juicy Bomb Shiny Tono 101 x 10ml', 'Añade un toque brillante y jugoso a tus labios con el brillo Juicy Bomb Shiny de Essence. - Brillo labial con acabado brillante - Tono: Tono 101 - Marca: Essence', 9200, '50.webp', 'cosmeticos', 1, 1, 1, 'Novaventa'),
(51, 51, 'Vogue', 'Pestañina Vogue Resist a Prueba De Agua x 9g', 'Permite que tus pestañas se vean como recién maquilladas levantadas y con volumen. A prueba de agua, sudor y humedad con color negro intenso.', 25000, '51.webp', 'cosmeticos', 1, 1, 1, 'Novaventa'),
(52, 52, 'Nosotras', 'Protectores Nosotras Diarios Largos x 50 unds', 'Los Protectores Nosotras Diarios Largos ofrecen mayor protección y frescura diaria gracias a su absorción superior y control de humedad y olores. Son 3 cm más largos que los protectores normales, con un diseño anatómico y adhesivo seguro que garantiza comodidad y ajuste durante todo el día, cuidando la piel con materiales suaves y transpirables.', 11000, '52.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(53, 53, 'Lubriderm', 'Crema Corporal Lubriderm Humectación Diaria x 120ml', 'Tecnología Pro-ceramidas que ayuda a mantener la piel humectada y protegida. Ayuda a restaurar la piel dejándola visiblemente saludable en 1 día. Fórmula ligera con glicerina y emolientes, de rápida absorción. Clínicamente y dermatológicamente probada.', 18600, '53.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(54, 54, 'Nutribela', 'Tratamiento Nutribela Biokeratina x300ml', 'Dale a tu cabello la nutrición profunda que necesita con la avanzada fórmula de Nutribela 10 Biokeratina. Este tratamiento combina 10 ingredientes reconocidos (como Biotina, Keratina y Vitamina E) para reparar intensamente la fibra capilar de raíz a puntas. Su componente principal, la Biokeratina, actúa rellenando los poros del cabello, devolviéndole su fuerza natural, brillo y sedosidad. Ideal para cabellos procesados, quebradizos o expuestos constantemente al calor.', 21000, '54.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(55, 55, 'Sedal', 'Crema para peinar Sedal Rizos Definidos x 300ml', 'ncluye elastina, una proteína con poder hidratante que ayuda a mantener la humedad del cabello. Enriquecido con provitamina B5, reconocida por su capacidad para hidratar profundamente el cabello.La fórmula ayuda a proteger, nutrir y definir los rizos. Ideal para el cuidado específico del cabello rizado.', 15000, '55.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(56, 56, 'Masglo', ' Brillo Masglo Gel Top x 13.5ml', 'Acabado multidimensional de alto brillo 4D: Brillo efecto espejo: Sella perfectamente las capas de esmalte, aportando un acabado liso, perfecto, profesional y de alto brillo. Efecto Volumen: La textura gel fluida de viscosidad moderada y su pincel plano lengua de gato permiten una fácil aplicación, con cobertura perfecta y volumen instantáneo. Larga Duración: Genera un escudo protector con gran resistencia al rayado, protegiendo el color de los daños ocasionados por el entorno, asegurando así colores más vivos y vibrantes por días. Rápido secado: Acelera el secado del esmalte. La presentación de 13.5 mL rinde aproximadamente 45 aplicaciones (manicure completo). No requiere secado en lámpara UV/LED, cura a la luz natural. Producto vegano. libre de Tolueno, Formaldehído, Resina de Formaldehído, Dibutil Ftalato (DBP), Alcanfor, Parabenos, Xileno, T', 12500, '56.webp', 'cosmeticos', 1, 1, 1, 'Novaventa'),
(57, 57, 'Nutribela', 'Acondicionador Células Madres Nutribela x370ml', 'Nutre y repara el cabello dañado, fortaleciéndolo desde la raíz hasta las puntas. Su fórmula con células madre y biokeratina aporta hidratación, controla el frizz y mejora la suavidad y el brillo. Es ideal para todo tipo de cabello y libre de crueldad animal.', 22000, '57.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(58, 58, 'Carefree', 'Protectores Carefree todos los días x 100 unds', 'Deja pasar 10 veces más el aire*. - Neutraliza Olores. - Respeta la temperatura natural de la zona íntima. - Respeta el pH natural de la zona íntima. - Sin Perfume. - Hipoalergénico. - Dermatológicamente probado. - Previene Irritaciones. (*vs Carefree® Protección).', 15500, '58.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(59, 59, 'Carefree', 'Protectores Carefree Protección x 100unds', 'Evitan filtraciones en caso de que tengas posibles descargas gracias a su barrera plástica que las retiene en el protector y fuera de tu ropa interior. Son ideales para usar como respaldo de tus tampones; logran neutralizar posibles olores y tienen una cubierta súper suave de algodón.', 15500, '59.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(60, 60, 'Mon Ami', 'Shampoo y acondicionador Mon Ami x 250ml', 'ara perros y gatos de todas las razas Fórmula libre de sal y parabenos Aroma neutro, agradable y durable Deja el pelo brillante y sedoso Aroma no invasivo para la mascota', 20000, '60.webp', 'mascotas', 1, 1, 1, 'Novaventa'),
(61, 61, 'Ruby Rose', 'Lip Oil Para Labios Ruby Rose Tono Fresa x 5.5ml', 'Brillo labial. Hidrata los labios, textura ligera y no pegajosa, no aporta color y diferentes aromas.', 20000, '61.webp', 'cosmeticos', 1, 1, 1, 'Novaventa'),
(62, 62, 'Nutribela', 'Crema para Peinar Nutribela Enzimoterapia x300ml', 'Es Una Solución Intensiva Diseñada Para Reparar Y Revitalizar La Fibra Capilar. Su Tecnología A Base De Enzimas Activas Ayuda A Fortalecer El Cabello Desde La Raíz Hasta Las Puntas, Brindando Una Hidratación Profunda Y Protección Contra El Quiebre.', 17000, '62.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(63, 63, 'Nutribela', 'Tratamiento Nutribela Pro Hialurónico x 300ml', 'Experimenta el poder de la hidratación profunda con Nutribela Pro Hialurónico. Su fórmula avanzada con Ácido Hialurónico actúa como un imán de humedad, rellenando la fibra capilar y eliminando la porosidad. Este tratamiento combina 10 ingredientes poderosos que transforman el cabello opaco y seco en una melena con movimiento, suavidad extrema y un brillo radiante. Es la solución perfecta para quienes buscan un cabello visiblemente más sano y con cuerpo.', 20000, '63.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(64, 64, 'Nutribela', 'Shampoo Células Madres Nutribela x400ml', 'Dale una nueva vida a tu cabello desde la raíz. El Shampoo Nutribela Células Madres combina una limpieza suave con el poder regenerativo de las células madre vegetales. Su fórmula exclusiva no solo limpia, sino que ayuda a fortalecer la fibra capilar, promoviendo un crecimiento saludable y previniendo el quiebre. Enriquecido con los 10 ingredientes icónicos de Nutribela, este shampoo es el primer paso para un cabello visiblemente más joven, fuerte y con una elasticidad renovada.', 24000, '64.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(65, 65, 'Nutribela', 'Shampoo Prohialurónico Nutribela x400ml', 'Logra una limpieza profundamente hidratante con el Shampoo Nutribela Pro Hialurónico. Diseñado para cabellos secos o deshidratados, su fórmula con Ácido Hialurónico actúa desde el lavado para retener la humedad natural del cabello, evitando la sensación de rigidez. Al combinar los 10 ingredientes nutritivos de Nutribela, este shampoo deja el cabello ligero, con movimiento y con un brillo radiante desde la raíz. Es el primer paso esencial para un ritual de belleza que transforma la fibra capilar.', 24000, '65.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(66, 66, 'Vogue', 'Esmalte Para Uñas Vogue Secado Rápido Tono Beso Picante x 12ml', 'Disfruta de una manicura perfecta sin perder tiempo ni gastar una fortuna. El nuevo esmalte de secado ultra rápido seca en tan solo 45 segundos, minimizando las manchas y los borrones para un acabado impecable y profesional desde casa. Su fórmula innovadora prolonga la vida de tu manicura al reducir el tiempo de exposición a posibles daños, permitiéndote volver a tus actividades diarias rápidamente sin preocuparte por estropear tus uñas.', 8500, '66.webp', 'cosmeticos', 1, 1, 1, 'Novaventa'),
(67, 67, 'Ego', 'Gel Ego Ultra Intense x 500ml', 'Diseñado para el hombre que exige un control total. El Gel Ego Ultra Intense ofrece el nivel de fijación más alto de la línea (Nivel 10), garantizando que tu peinado se mantenga firme y en su lugar sin importar las condiciones del día. Su fórmula avanzada no deja residuos blancos, protege la fibra capilar y aporta un brillo saludable con una fragancia intensamente masculina. Ideal para estilos estructurados que requieren resistencia extrema y larga duración.', 18000, '67.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(68, 68, 'Anyeluz', 'Fijador De Cejas Anyeluz Tono Castaño Medio x 5.3ml', 'Logra unas cejas perfectas, definidas y con un aspecto natural durante todo el día. El fijador de Anyeluz en tono Castaño Medio es ideal para rellenar espacios vacíos y mantener cada vello en su lugar sin dejar una sensación rígida o pegajosa. Su fórmula de larga duración es resistente al roce y ayuda a enmarcar tu mirada con precisión. Gracias a su cepillo aplicador de alta definición, podrás lucir unas cejas pobladas y organizadas en cuestión de segundos.', 12000, '68.webp', 'cosmeticos', 1, 1, 1, 'Novaventa'),
(69, 69, 'Johnson\'s', 'Shampoo Johnson\'s Manzanilla x 400 ml', 'Realza el brillo natural del cabello de tu bebé con la suavidad que solo Johnson\'s puede ofrecer. Este shampoo está enriquecido con extracto natural de manzanilla, ayudando a limpiar delicadamente mientras mantiene los tonos claros brillantes y sedosos. Su exclusiva fórmula \"No Más Lágrimas\" permite una experiencia de baño tranquila y sin irritaciones en los ojos. Es hipoalergénico, libre de colorantes, parabenos y sulfatos, garantizando un cuidado puro y seguro para el cabello más fino.', 31000, '69.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(70, 70, 'Nutribela', 'Acondicionador Nutribela Biokeratina x370ml', 'Logra un desenredo instantáneo y una suavidad superior con el Acondicionador Nutribela Biokeratina. Diseñado para complementar el proceso de reparación capilar, este acondicionador sella las cutículas del cabello, atrapando los beneficios de la biokeratina y los 10 nutrientes esenciales en el interior de la fibra. El resultado es un cabello mucho más resistente al quiebre, con un brillo intenso y una textura sedosa que facilita el peinado diario. Ideal para mantener el control del frizz y devolverle la vitalidad al cabello dañado.', 22000, '70.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(71, 71, 'Nutribela', 'Acondicionador Nutribela Reparación Intensiva x 370ml', 'Devuélvele la vida a tu cabello con el poder de la nutrición avanzada. Este acondicionador está formulado para sellar instantáneamente la fibra capilar, facilitando el desenredo y previniendo el quiebre. Su tecnología de reparación intensiva combina 10 ingredientes poderosos que trabajan en conjunto para suavizar la cutícula y devolverle la elasticidad al cabello maltratado. Disfruta de una melena sedosa, con menos frizz y un brillo saludable desde el primer uso.', 22000, '71.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(72, 72, 'Vogue', 'Esmalte Para Uñas Vogue Secado Rápido Tono Rojo Antojo x 12ml', 'Disfruta de una manicura perfecta sin perder tiempo ni gastar una fortuna. El nuevo esmalte de secado ultra rápido seca en tan solo 45 segundos, minimizando las manchas y los borrones para un acabado impecable y profesional desde casa. Su fórmula innovadora prolonga la vida de tu manicura al reducir el tiempo de exposición a posibles daños, permitiéndote volver a tus actividades diarias rápidamente sin preocuparte por estropear tus uñas.', 8500, '72.webp', 'cosmeticos', 1, 1, 1, 'Novaventa'),
(73, 73, 'Vogue', 'Esmalte Para Uñas Vogue Secado Rápido Tono Caribe Sazón x 12ml', 'Disfruta de una manicura perfecta sin perder tiempo ni gastar una fortuna. El nuevo esmalte de secado ultra rápido seca en tan solo 45 segundos, minimizando las manchas y los borrones para un acabado impecable y profesional desde casa. Su fórmula innovadora prolonga la vida de tu manicura al reducir el tiempo de exposición a posibles daños, permitiéndote volver a tus actividades diarias rápidamente sin preocuparte por estropear tus uñas.', 8500, '73.webp', 'cosmeticos', 1, 1, 1, 'Novaventa'),
(74, 74, 'Milagros', 'Acondicionador Milagros Herbal x450ml', 'Si buscas suavidad inmediata y menos frizz sin dejar el cabello pesado, el Acondicionador Milagros Herbal puede ser una gran opción. Ayuda a desenredar fácilmente, aportar brillo y deja el cabello con sensación fresca y manejable. Desenreda al instante, ayuda a reducir el frizz y aporta brillo visible sin apelmazar. Uso: Aplica de medios a puntas (evita la raíz si es graso), deja actuar **2-3 minutos** (hasta 5 min si está muy seco) y enjuaga. ', 35000, '74.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(75, 75, 'Tío Nacho', 'Shampoo Tío Nacho Engrosador x 415ml', 'Dale a tu cabello la abundancia y el cuerpo que siempre has deseado. El Shampoo Tío Nacho Engrosador combina siglos de conocimiento herbal con la exclusividad de la Jalea Real y extractos de origen natural como el Lúpulo y la Quina. Su fórmula actúa fortaleciendo cada hebra capilar, aumentando el diámetro del cabello y reduciendo la caída por quiebre. El resultado es una cabellera visiblemente más abundante, resistente y con un brillo saludable que destaca desde el primer uso.', 39000, '75.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(76, 76, 'Tío Nacho', 'Shampoo Tío Nacho Anti-Canas x 1L', 'Recupera el tono de tu cabello de forma natural y progresiva. El Shampoo Tío Nacho Anti-Canas combina la nutrición de la Jalea Real con extractos de Henna vegetal para matizar las canas y unificar el tono del cabello oscuro. Su fórmula fortalece la fibra capilar, previene la caída por quiebre y deja el cabello suave y brillante. Al ser una presentación de 1 Litro, es la opción más económica y duradera para el cuidado diario de toda la familia, brindando resultados visibles lavado tras lavado.', 52000, '76.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(77, 77, 'Ruby Rose', 'Rubor En Barra Ruby Rose Tono Soft Pink x 6.57g', 'Con Una Fórmula Suave E Hidratante, El Rubor En Barra Dreamy Cheecks Es Ideal Para Aportar Color A La Piel, Devolviéndole El Aspecto Saludable Del Rostro. Presenta Una Textura Cremosa Que Se Desliza Con Facilidad Y Se Funde A La Perfección Con La Piel Para Crear Un Color Radiante Y Natural.', 27000, '77.webp', 'cosmeticos', 1, 1, 1, 'Novaventa'),
(78, 78, 'Vogue', 'Esmalte Para Uñas Vogue Secado Rápido Tono Pacifica x 12ml', 'Disfruta de una manicura perfecta sin perder tiempo ni gastar una fortuna. El nuevo esmalte de secado ultra rápido seca en tan solo 45 segundos, minimizando las manchas y los borrones para un acabado impecable y profesional desde casa. Su fórmula innovadora prolonga la vida de tu manicura al reducir el tiempo de exposición a posibles daños, permitiéndote volver a tus actividades diarias rápidamente sin preocuparte por estropear tus uñas.', 8500, '78.webp', 'cosmeticos', 1, 1, 1, 'Novaventa'),
(79, 79, 'Essence', 'Brillo Essence Juicy Bomb Tono 106 x 10ml', '¡Dale a tus labios una explosión de brillo y sabor! El Juicy Bomb de Essence es el gloss ultra brillante que se ha vuelto viral gracias a su textura no pegajosa y su acabado tipo \"espejo\". El Tono 106 ofrece un color sutil y encantador con un aroma frutal irresistible. Su fórmula ligera se desliza suavemente, dejando los labios hidratados, suaves y con un volumen visual increíble. Es el accesorio de belleza imprescindible para llevar en el bolso y lucir unos labios frescos en cualquier momento.', 9200, '79.webp', 'cosmeticos', 1, 1, 1, 'Novaventa'),
(80, 80, 'Nosotras', 'Toallas Higiénicas Nosotras Invisible Rapigel x 40 unds', 'ofrecen una absorción rápida gracias a su tecnología Rapigel, manteniéndote seca y fresca todo el día. Su diseño delgado e invisible brinda comodidad sin sensación de volumen, mientras que su adhesivo seguro evita filtraciones. Además, controlan olores para que te sientas protegida y segura en cualquier momento.', 26500, '80.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(81, 81, 'Nosotras', 'Toallas Higiénicas Nosotras Buenas Noches tela x 24 unds', 'Ofrecen protección segura y cómoda durante la noche. Su suave cubierta con aloe vera y manzanilla cuida y calma la piel, mientras su diseño con alas anchas y centro elevado evita filtraciones. Perfectas para mantenerte fresca, protegida y sin molestias mientras duermes.', 25000, '81.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(82, 82, 'Johnson\'s', 'Shampoo Johnson\'s Manzanilla x 200ml', 'Realza el brillo natural del cabello de tu bebé con la suavidad que solo Johnson\'s puede ofrecer. Este shampoo está enriquecido con extracto natural de manzanilla, ayudando a limpiar delicadamente mientras mantiene los tonos claros brillantes y sedosos. Su exclusiva fórmula \"No Más Lágrimas\" permite una experiencia de baño tranquila y sin irritaciones en los ojos. Es hipoalergénico, libre de colorantes, parabenos y sulfatos, garantizando un cuidado puro y seguro para el cabello más fino.', 20000, '82.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(83, 83, 'Essence', 'Paleta De Sombras Essence Tono Nude x 10g', 'Crea looks infinitos, desde un acabado mate hasta un perlado. Una variedad de tonos nude y de suaves a rosados intensos. Tonos de gran pigmentación', 27600, '83.webp', 'cosmeticos', 1, 1, 1, 'Novaventa'),
(84, 84, 'Vogue', 'Esmalte Para Uñas Vogue Secado Rápido Tono Latin Fiesta x 12ml', 'Disfruta de una manicura perfecta sin perder tiempo ni gastar una fortuna. El nuevo esmalte de secado ultra rápido seca en tan solo 45 segundos, minimizando las manchas y los borrones para un acabado impecable y profesional desde casa. Su fórmula innovadora prolonga la vida de tu manicura al reducir el tiempo de exposición a posibles daños, permitiéndote volver a tus actividades diarias rápidamente sin preocuparte por estropear tus uñas.', 8500, '84.webp', 'cosmeticos', 1, 1, 1, 'Novaventa'),
(85, 85, 'Nutribela', 'Crema para Peinar Nutribela Reparación Intensiva x300ml', '¡Dale a tu cabello el cuidado que merece sin necesidad de enjuague! La crema para peinar Nutribela Reparación Intensiva combina 10 ingredientes poderosos (incluyendo Biotina, Keratina y Aloe Vera) para restaurar la fibra capilar desde el primer uso. Su fórmula ligera ayuda a desenredar fácilmente, controla el volumen y deja el cabello manejable, suave y con un aroma delicioso que perdura todo el día. Es perfecta para cabellos secos o maltratados que necesitan un extra de hidratación diaria.', 17000, '85.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(86, 86, 'Essence', 'Paleta De Sombras Essence Tono Rose x 10g', 'Desde un acabado mate hasta un perlado. Una variedad de tonos nude y de suaves a rosados intensos. Tonos de gran pigmentación', 27600, '86.webp', 'cosmeticos', 1, 1, 1, 'Novaventa'),
(87, 87, 'Vogue', ' Esmalte Para Uñas Vogue Secado Rápido Tono Arenita Playita x 12ml', 'Disfruta de una manicura perfecta sin perder tiempo ni gastar una fortuna. El nuevo esmalte de secado ultra rápido seca en tan solo 45 segundos, minimizando las manchas y los borrones para un acabado impecable y profesional desde casa. Su fórmula innovadora prolonga la vida de tu manicura al reducir el tiempo de exposición a posibles daños, permitiéndote volver a tus actividades diarias rápidamente sin preocuparte por estropear tus uñas.', 8500, '87.webp', 'cosmeticos', 1, 1, 1, 'Novaventa'),
(88, 88, 'Nutribela', 'Tratamiento Nutribela Reparación Intensiva x 300ml', 'Transforma tu cabello con el poder de la nutrición avanzada. Nutribela 10 combina diez de los ingredientes más reconocidos en el mundo de la cosmética capilar (Sábila, Keratina, Biotina, Vitamina E, Aceite de Coco, Colágeno, Argán, Karité, Silicona y Proteína de Seda) en una sola fórmula de reparación profunda. Este tratamiento intensivo penetra en la fibra capilar para reparar el daño, sellar las cutículas y devolver el brillo perdido. Es el \"socorro\" semanal que tu cabello necesita para lucir sano, fuerte y radiante.', 18900, '88.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(89, 89, 'Bayer', 'Alka-Seltzer x 14 Tabletas', '¡Recupera tu bienestar al instante! Alka-Seltzer es la solución efervescente que combate de forma rápida y efectiva la acidez, la indigestión ácida y el malestar estomacal. Su fórmula burbujeante actúa neutralizando el exceso de ácido en el estómago, brindando una sensación de alivio y frescura. La caja de 14 tabletas es el tamaño perfecto para tener siempre a mano en el botiquín familiar, asegurando que tú y tu familia estén protegidos tras esas comidas especiales o excesos ocasionales.', 20900, '89.webp', 'farmacia', 1, 1, 1, 'Novaventa'),
(90, 90, 'Mon Ami', ' Eliminador de Olores Mon Ami x400ml', 'Fórmula 3 en 1: Desinfecta, elimina olores y ambienta     Momento de relajación a través de la aromaterapia     Con aceites esenciales de Ylang Ylang y Limón     Frgancia exclusiva con notas de lavanda, flor de naranjo, bergamota y sándalo.     Elimina hongos y bacterias', 15400, '90.webp', 'mascotas', 1, 1, 1, 'Novaventa'),
(91, 91, 'Nivea', 'Bálsamo para labios Nivea Fresa x 4.8g', '¡Manten tus labios hidratados y con un toque de color natural! El bálsamo Nivea Fresa ofrece 24 horas de hidratación profunda gracias a su fórmula con aceites de origen natural y manteca de karité. Su delicioso aroma a fresa y su sutil pigmento rojizo realzan la belleza natural de tus labios mientras los protegen del frío, el viento y la resequedad. No contiene aceites minerales, es de fácil aplicación y el tamaño perfecto para llevar en el bolsillo o bolso.', 19800, '91.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(92, 92, 'Tío Nacho', 'Acondicionador Tío Nacho Engrosador x 415ml', '¡Dale cuerpo y fuerza a tu cabello! El acondicionador Tío Nacho Engrosador está diseñado para complementar el tratamiento anticaída, proporcionando una hidratación profunda sin dejar el cabello pesado. Su fórmula con Jalea Real y una exclusiva combinación de extractos de origen natural actúa sobre cada hebra para aumentar su diámetro, dando como resultado un cabello visiblemente más abundante y resistente desde el primer mes de uso. Desenreda suavemente mientras previene la rotura, dejando tu melena suave, brillante y con mucho más volumen.', 38900, '92.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(93, 93, 'Listerine', 'Enjuague Bucal Listerine Cool Mint x 180ml', '¡Lleva tu higiene oral al siguiente nivel! Listerine Cool Mint elimina hasta el 99% de los gérmenes que causan el mal aliento, la placa y la enfermedad de las encías. Su fórmula única a base de aceites esenciales llega a donde el cepillo y el hilo dental no pueden, garantizando una boca limpia y un aliento fresco por mucho más tiempo. El tamaño de 180ml es práctico, ergonómico y perfecto para mantener la rutina de limpieza profunda en el hogar o llevar en el equipaje.', 13500, '93.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(94, 94, 'Tío Nacho', 'Acondicionador Keratina Tío Nacho x415ml', '¡Reparación intensa desde la raíz hasta las puntas! El acondicionador Tío Nacho Keratina combina la ciencia de la Keratina Vegetal con el poder milenario de la Jalea Real orgánica. Su fórmula avanzada penetra en la fibra capilar dañada, sellando las cutículas y devolviendo la hidratación perdida. Proporciona un brillo espejo, suavidad extrema y facilita el peinado, protegiendo el cabello de futuras agresiones externas. Es el aliado ideal para lucir una melena sana, hidratada y visiblemente más joven.', 29500, '94.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(95, 95, 'Rexona', 'Desodorante tubo Rexona Clinical Clean x 30g', '¡Protección infalible para los retos más exigentes! Rexona Clinical ofrece una protección hasta 3 veces más fuerte que un antitranspirante común. Su avanzada fórmula en crema (tubo) forma una barrera contra el sudor y el mal olor, manteniéndote seco y fresco hasta por 96 horas. A pesar de su potencia, es suave con la piel gracias a sus ingredientes humectantes, lo que lo hace ideal para el uso diario incluso después de la depilación. La fragancia Clean es discreta, fresca y brinda una sensación de limpieza duradera.', 4500, '95.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(96, 96, 'Johnson\'s', 'Crema líquida Johnson\'s Original x 200ml', 'La suavidad que conoces y en la que confías. La crema líquida Johnson\'s Original está especialmente diseñada para hidratar la delicada piel del bebé, dejándola suave y con ese aroma inconfundible a \"bebé limpio\". Su fórmula es hipoalergénica, libre de colorantes, parabenos y ftalatos, lo que garantiza un cuidado seguro desde el primer día de vida. Su textura ligera se absorbe rápidamente sin dejar sensación grasosa, ayudando a mantener la barrera natural de la piel protegida durante todo el día. Ideal para el masaje diario después del baño.', 21000, '96.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(97, 97, 'Speed Stick', 'Desodorante Lady Speed Stick Clinical Practitubo x 100g', '¡Máxima protección que rinde mucho más! Lady Speed Stick Clinical combina la eficacia de un antitranspirante de grado médico con un formato Practitubo de 100g, diseñado para quienes buscan economía sin sacrificar seguridad. Su avanzada fórmula actúa contra el sudor y el mal olor incluso en situaciones de estrés o actividad física intensa. Proporciona una barrera seca y una fragancia femenina de larga duración, cuidando la piel de tus axilas para que te sientas segura y protegida durante todo el día.', 14000, '97.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(98, 98, 'Speed Stick', 'Desodorante Speed Stick Clinical Practitubo x 100g', '¡Rendimiento extremo para el hombre imparable! Speed Stick Clinical ofrece una protección de nivel superior contra la transpiración y el mal olor, incluso en los días de mayor actividad física o estrés. Su fórmula avanzada de grado clinical se presenta en un generoso formato Practitubo de 100g, ofreciendo el equilibrio perfecto entre eficacia profesional y ahorro. Se aplica suavemente, se seca rápido y te mantiene ultra seco con una fragancia masculina clásica que proyecta limpieza y seguridad desde la mañana hasta la noche.', 14000, '98.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(99, 99, 'Speed Stick', ' Desodorante Lady Speed Stick Protege y Aclara Practitubo x 100g', '¡Recupera el tono natural de tu piel mientras te mantienes protegida! El desodorante Lady Speed Stick Protege y Aclara está diseñado para ayudar a reducir las manchas oscuras en las axilas causadas por el rasurado, gracias a su fórmula con extractos aclarantes. Su presentación en Practitubo de 100g ofrece una textura en crema suave que hidrata la zona, brindando protección efectiva contra el sudor y el mal olor hasta por 48 horas. Es la combinación perfecta entre un tratamiento de belleza y un antitranspirante de alta confianza.', 14000, '99.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(100, 100, 'Nutribela', 'Crema para Peinar Nutribela Biokeratina x300ml', 'Repara, Nutre Y Fortalece Profundamente, Dejando Tu Cabello Suave, Liso Y Manejable. Ideal Para Combatir El Frizz', 17500, '100.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(101, 101, 'Mexsana', 'Talco Mexsana Antibacterial x 85g', 'Efectiva protección antibacterial y desodorante para los pies de toda la familia. Mexsana, una costumbre fresca y sana. Además: - Previene la aparición de hongos y elimina las bacterias causantes del sudor y mal olor - Rápido secado, sin dejar huella - Deja en la piel una sensación suave, limpia y fresca Incluye: 1 Talco Mexsana Antibacterial x 85g', 14600, '101.webp', 'cuidado-personal', 1, 1, 1, 'Novaventa'),
(102, 102, 'Vogue', 'Esmalte Para Uñas Vogue Secado Rápido Tono Noche Estrellada x 12ml', 'Disfruta de una manicura perfecta sin perder tiempo ni gastar una fortuna. El nuevo esmalte de secado ultra rápido seca en tan solo 45 segundos, minimizando las manchas y los borrones para un acabado impecable y profesional desde casa. Su fórmula innovadora prolonga la vida de tu manicura al reducir el tiempo de exposición a posibles daños, permitiéndote volver a tus actividades diarias rápidamente sin preocuparte por estropear tus uñas.', 8500, '102.webp', 'cosmeticos', 1, 1, 1, 'Novaventa'),
(103, 103, 'Essence', 'Brillo Essence Juicy Bomb Shiny Tono 104 x 10ml', '¡Dale a tus labios un brillo explosivo y un aroma delicioso! El Juicy Bomb Tono 104 ofrece un acabado ultra brillante con un sutil toque de color rojizo cereza que se adapta a cualquier tono de piel. Su fórmula no pegajosa se desliza suavemente, proporcionando una sensación de hidratación y un efecto visual de labios más voluminosos. Es el accesorio perfecto para llevar en el bolso, ideal para un look fresco y natural durante el día o para añadir un toque \"glossy\" sobre tu labial favorito.', 9200, '103.webp', 'cosmeticos', 1, 1, 1, 'Novaventa');

--
-- Índices para tablas volcadas
--

--
-- Indices de la tabla `producto`
--
ALTER TABLE `producto`
  ADD PRIMARY KEY (`id_producto`),
  ADD UNIQUE KEY `UC_Imagen_Producto` (`imagen_producto`),
  ADD UNIQUE KEY `codigo de barras` (`codigo_barras_producto`);

--
-- AUTO_INCREMENT de las tablas volcadas
--

--
-- AUTO_INCREMENT de la tabla `producto`
--
ALTER TABLE `producto`
  MODIFY `id_producto` int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=104;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
